CREATE DATABASE IF NOT EXISTS sistema_nomina
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE sistema_nomina;


SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `tipo_aumento` (
  `TIPO_AUMENTO_ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`TIPO_AUMENTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tipo_empleado` (
  `ID_TIPO_EMPLEADO` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(1000) NOT NULL,
  PRIMARY KEY (`ID_TIPO_EMPLEADO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tipo_ausencia` (
  `id_tipo_ausencia` int NOT NULL AUTO_INCREMENT,
  `descripcion_corta` varchar(45) DEFAULT NULL,
  `descripcion_larga` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id_tipo_ausencia`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tipo_pago` (
  `ID_TIPO_PAGO` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(200) NOT NULL,
  PRIMARY KEY (`ID_TIPO_PAGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tipo_pago_empleado` (
  `id_tipo_pago_empleado` int NOT NULL AUTO_INCREMENT,
  `descripcion` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id_tipo_pago_empleado`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tipo_jornada` (
  `id_tipo_jornada` int NOT NULL AUTO_INCREMENT,
  `descripcion` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id_tipo_jornada`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tipo_pago_prestamo` (
  `ID_TIPO_PAGO_PRESTAMO` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_PAGO_PRESTAMO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `forma_pago` (
  `ID_TIPO_PAGO` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(1000) NOT NULL,
  PRIMARY KEY (`ID_TIPO_PAGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `categoria` (
  `ID_CAT` int NOT NULL AUTO_INCREMENT,
  `COD_CAT` varchar(3) NOT NULL,
  `NOM_CAT` varchar(30) NOT NULL,
  `SAL_INI` decimal(17,2) NOT NULL COMMENT 'salario inicial',
  `SAL_FIN` decimal(17,2) NOT NULL COMMENT 'salario final',
  PRIMARY KEY (`ID_CAT`),
  UNIQUE KEY `COD_CATEGORIA_UNIQUE` (`COD_CAT`),
  UNIQUE KEY `NOM_CAT_UNIQUE` (`NOM_CAT`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `empleado` (
  `ID_TRB` int NOT NULL AUTO_INCREMENT,
  `COD_TRB` varchar(5) NOT NULL,
  `NOM_TRB` varchar(50) NOT NULL,
  `PUESTO_TRABAJO` varchar(100) DEFAULT NULL,
  `FEC_NAC` date NOT NULL,
  `IDEN_TRB` varchar(20) NOT NULL,
  `EST_TRB` varchar(1) NOT NULL,
  `TELEFONO` varchar(14) DEFAULT NULL,
  `CELULAR` varchar(15) DEFAULT NULL,
  `PASAPORTE` varchar(20) DEFAULT NULL,
  `RTN` varchar(15) DEFAULT NULL,
  `RESIDENCIA` varchar(20) DEFAULT NULL,
  `ANTECEDENTES` varchar(8) DEFAULT NULL,
  `IHS` varchar(13) DEFAULT NULL,
  `DIRECCION` varchar(40) NOT NULL,
  `FEC_DEF` date NOT NULL,
  `SEXO` varchar(1) NOT NULL,
  `SUELDO` decimal(17,2) NOT NULL,
  `AFECTA_IHS` varchar(1) NOT NULL,
  `AFECTA_FSV` varchar(1) NOT NULL,
  `AFECTA_IPP` varchar(1) DEFAULT NULL,
  `AFECTA_SIN` varchar(1) NOT NULL,
  `AFECTA_ISR` varchar(1) NOT NULL,
  `BANCOS` varchar(15) DEFAULT NULL,
  `NCUENTA` varchar(13) DEFAULT NULL,
  `COD_CUE` varchar(8) DEFAULT NULL,
  `ESTADO` varchar(1) DEFAULT NULL,
  `LICENCIA` varchar(15) DEFAULT NULL,
  `ID_DEP` int NOT NULL,
  `ID_CAT` int NOT NULL,
  `ID_TIPO_EMPLEADO` int NOT NULL,
  `ID_TIPO_PAGO` int NOT NULL,
  `TIPO_EMPLEADO` varchar(1) NOT NULL,
  `FECHA_CONTRATACION` date NOT NULL,
  `FECHA_INICIO` date NOT NULL,
  `CUENTA_SUELDO` decimal(17,2) DEFAULT NULL,
  `CUENTA_SEGURO_SOCIAL` decimal(17,2) DEFAULT NULL,
  `CUENTA_REGIMEN_ESPECIAL` decimal(17,2) DEFAULT NULL,
  `CUENTA_ISR` decimal(17,2) DEFAULT NULL,
  `OTRA_CUENTA_1` decimal(17,2) DEFAULT NULL,
  `OTRA_CUENTA_2` decimal(17,2) DEFAULT NULL,
  PRIMARY KEY (`ID_TRB`),
  UNIQUE KEY `EMPLEADO_UNIQUE` (`COD_TRB`),
  UNIQUE KEY `uq_empleado_dni` (`IDEN_TRB`),
  UNIQUE KEY `uq_empleado_rtn` (`RTN`),
  KEY `fk_empleado_tipo_empleado` (`ID_TIPO_EMPLEADO`),
  KEY `fk_empleado_departamento` (`ID_DEP`),
  KEY `fk_empleado_f_pago_id_forma_pago_idx` (`ID_TIPO_PAGO`),
  KEY `fk_empleado_categoria` (`ID_CAT`),
  CONSTRAINT `fk_empleado_categoria` FOREIGN KEY (`ID_CAT`) REFERENCES `categoria` (`ID_CAT`),
  CONSTRAINT `fk_empleado_depto_id_depto` FOREIGN KEY (`ID_DEP`) REFERENCES `departamento` (`ID_DEP`),
  CONSTRAINT `fk_empleado_forma_pago_id` FOREIGN KEY (`ID_TIPO_PAGO`) REFERENCES `forma_pago` (`ID_TIPO_PAGO`),
  CONSTRAINT `fk_empleado_tipo_empleado` FOREIGN KEY (`ID_TIPO_EMPLEADO`) REFERENCES `tipo_empleado` (`ID_TIPO_EMPLEADO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `departamento` (
  `ID_DEP` int NOT NULL AUTO_INCREMENT,
  `COD_DEP` varchar(3) NOT NULL,
  `NOM_DEP` varchar(30) NOT NULL,
  `ID_EMPLEADO` int DEFAULT NULL COMMENT 'nombre encargado',
  `ID_CUENTA` int DEFAULT NULL COMMENT 'codigo cuenta',
  PRIMARY KEY (`ID_DEP`),
  UNIQUE KEY `COD_DEP_UNIQUE` (`COD_DEP`),
  UNIQUE KEY `NOM_DEP_UNIQUE` (`NOM_DEP`),
  KEY `fk_empleado_id_encargado_jefe_idx` (`ID_EMPLEADO`),
  CONSTRAINT `fk_departamento` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_TRB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `antecedentes` (
  `ID_ANTECEDENTE` int NOT NULL AUTO_INCREMENT,
  `NUMERO_ANTECEDENTE` int NOT NULL,
  `FECHA_EMISION` date NOT NULL,
  `FECHA_VENCIMIENTO` date NOT NULL,
  `VIGENCIA` date NOT NULL,
  `LUGAR_ORIGEN` varchar(100) NOT NULL,
  `ID_EMPLEADO` int NOT NULL,
  `TIPO_ANTECEDENTE` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`ID_ANTECEDENTE`),
  UNIQUE KEY `NUMERO_ANTECENDENTE` (`NUMERO_ANTECEDENTE`),
  KEY `FK_ANTECENDENTE_EMPLEADO_idx` (`ID_EMPLEADO`),
  CONSTRAINT `FK_ANTECENDENTE_EMPLEADO` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_TRB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `aumentos` (
  `AUMENTOS_ID` int NOT NULL AUTO_INCREMENT,
  `ID_EMPLEADO` int NOT NULL,
  `ID_CATEGORIA` int NOT NULL,
  `FECHA` datetime NOT NULL,
  `SUELDO_ANTERIOR` decimal(17,2) NOT NULL,
  `SUELDO_ACTUAL` decimal(17,2) NOT NULL,
  `TIPO_AUMENTO_ID` int NOT NULL,
  `PORCENTAJE` decimal(13,3) DEFAULT NULL,
  `MONTO` decimal(17,2) DEFAULT NULL,
  `TOTAL_MONTO` decimal(17,2) NOT NULL,
  `DESCRIPCION` varchar(30) NOT NULL,
  PRIMARY KEY (`AUMENTOS_ID`),
  KEY `FK_AUMENTOS_CATEGORIA` (`ID_CATEGORIA`),
  KEY `FK_AUMENTOS_EMPLEADO` (`ID_EMPLEADO`),
  KEY `FK_AUMENTOS_TIPO_AUMENTO_idx` (`TIPO_AUMENTO_ID`),
  CONSTRAINT `FK_AUMENTOS_CATEGORIA` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `categoria` (`ID_CAT`),
  CONSTRAINT `FK_AUMENTOS_EMPLEADO` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_TRB`),
  CONSTRAINT `FK_AUMENTOS_TIPO_AUMENTO` FOREIGN KEY (`TIPO_AUMENTO_ID`) REFERENCES `tipo_aumento` (`TIPO_AUMENTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ausencias` (
  `AUSENCIAS_ID` int NOT NULL AUTO_INCREMENT,
  `ID_EMPLEADO` int NOT NULL,
  `FECHA_INICIAL` date NOT NULL COMMENT 'FECHA DE INICIO DE AUSENCIA',
  `FECHA_FINAL` date NOT NULL COMMENT 'FECHA DE FINALIZACIÓN DE AUSENCIA',
  `NUMERO_DIAS_TRABAJADOS` int NOT NULL COMMENT 'NUMERO DE DIAS NO TRABAJADOS',
  `MONTO` decimal(17,2) NOT NULL COMMENT 'MONTO',
  `TIPO_AUSENCIA` int DEFAULT NULL,
  `ID_NOMINA` int NOT NULL COMMENT 'CODIGO NOMINA',
  `ID_TIPO_NOM` int DEFAULT NULL,
  `SEPTIMO` varchar(1) DEFAULT NULL,
  `ID_TIPO_AUSENCIA` int NOT NULL,
  PRIMARY KEY (`AUSENCIAS_ID`),
  KEY `FK_AUSENCIAS_EMPLEADO` (`ID_EMPLEADO`),
  KEY `FK_AUSENCIAS_TIPO_AUSENCIA_idx` (`ID_TIPO_AUSENCIA`),
  CONSTRAINT `FK_AUSENCIAS_EMPLEADO` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_TRB`),
  CONSTRAINT `FK_AUSENCIAS_TIPO_AUSENCIA` FOREIGN KEY (`ID_TIPO_AUSENCIA`) REFERENCES `tipo_ausencia` (`id_tipo_ausencia`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `descuento` (
  `ID_DESCUENTO` int NOT NULL AUTO_INCREMENT,
  `COD_DEC` varchar(3) NOT NULL,
  `NOM_DEC` varchar(30) NOT NULL,
  `VAL_DEC` decimal(17,2) DEFAULT NULL COMMENT 'VALOR DEL DESCUENTO',
  `FAC_DEC` decimal(17,7) DEFAULT NULL,
  `ID_TIPO_JORNADA` int NOT NULL COMMENT 'TIPOD DE JORNADA',
  `ID_TIPO_PAGO` int NOT NULL COMMENT 'TIPO DE DESCUENTO',
  `ID_COD_CUE` int DEFAULT NULL,
  PRIMARY KEY (`ID_DESCUENTO`),
  UNIQUE KEY `codigo_unique` (`COD_DEC`),
  UNIQUE KEY `nombre_unique` (`NOM_DEC`),
  KEY `fk_descuento_tipo_jornada_idx` (`ID_TIPO_JORNADA`),
  KEY `descuento_ibfk_1` (`ID_TIPO_PAGO`),
  CONSTRAINT `descuento_ibfk_1` FOREIGN KEY (`ID_TIPO_PAGO`) REFERENCES `tipo_pago` (`ID_TIPO_PAGO`),
  CONSTRAINT `fk_descuento_tipo_jornada` FOREIGN KEY (`ID_TIPO_JORNADA`) REFERENCES `tipo_jornada` (`id_tipo_jornada`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `error_log` (
  `error_id` int NOT NULL AUTO_INCREMENT,
  `mensaje` varchar(10000) DEFAULT NULL,
  `tabla` varchar(45) DEFAULT NULL,
  `nombre_columna` varchar(45) DEFAULT NULL,
  `codigo_error` varchar(45) DEFAULT NULL,
  `fecha_error` timestamp NULL DEFAULT NULL,
  `valor_campo` text,
  `accion` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`error_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `historial_aumento` (
  `ID_EMPLEADO` int NOT NULL,
  `ID_CAT` int NOT NULL,
  `FECHA` datetime NOT NULL,
  `SUELDO_ANTERIOR` decimal(10,0) NOT NULL,
  `SUELDO_ACTUAL` decimal(10,0) NOT NULL,
  `MONTO` decimal(10,0) NOT NULL,
  PRIMARY KEY (`ID_EMPLEADO`,`ID_CAT`,`FECHA`),
  UNIQUE KEY `historial_aumento_unique` (`ID_EMPLEADO`,`ID_CAT`,`FECHA`),
  KEY `fk_historial_aumento_categoria_idx` (`ID_CAT`),
  CONSTRAINT `fk_historial_aumento_categoria` FOREIGN KEY (`ID_CAT`) REFERENCES `categoria` (`ID_CAT`),
  CONSTRAINT `fk_historial_aumento_empleado` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_TRB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `historial_sueldo` (
  `HISTORIAL_SUELDO_ID` int NOT NULL AUTO_INCREMENT,
  `ID_EMPLEADO` int NOT NULL,
  `PERIODO` int DEFAULT NULL,
  `ENERO` decimal(17,2) DEFAULT NULL,
  `FEBRERO` decimal(17,2) DEFAULT NULL,
  `MARZO` decimal(17,2) DEFAULT NULL,
  `ABRIL` decimal(17,2) DEFAULT NULL,
  `MAYO` decimal(17,2) DEFAULT NULL,
  `JUNIO` decimal(17,2) DEFAULT NULL,
  `JULIO` decimal(17,2) DEFAULT NULL,
  `AGOSTO` decimal(17,2) DEFAULT NULL,
  `SEPTIEMBRE` decimal(17,2) DEFAULT NULL,
  `OCTUBRE` decimal(17,2) DEFAULT NULL,
  `NOVIEMBRE` decimal(17,2) DEFAULT NULL,
  `DICIEMBRE` decimal(17,2) DEFAULT NULL,
  `TOTAL` decimal(17,2) DEFAULT NULL,
  `ISR_ENERO` decimal(17,2) DEFAULT NULL,
  `ISR_FEBRERO` decimal(17,2) DEFAULT NULL,
  `ISR_MARZO` decimal(17,2) DEFAULT NULL,
  `ISR_ABRIL` decimal(17,2) DEFAULT NULL,
  `ISR_MAYO` decimal(17,2) DEFAULT NULL,
  `ISR_JUNIO` decimal(17,2) DEFAULT NULL,
  `ISR_JULIO` decimal(17,2) DEFAULT NULL,
  `ISR_AGOSTO` decimal(17,2) DEFAULT NULL,
  `ISR_SEPTIEMRE` decimal(17,2) DEFAULT NULL,
  `ISR_OCTUBRE` decimal(17,2) DEFAULT NULL,
  `ISR_NOVIEMBRE` decimal(17,2) DEFAULT NULL,
  `ISR_DICIEMBRE` decimal(17,2) DEFAULT NULL,
  `ISR_ANUAL` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`HISTORIAL_SUELDO_ID`),
  UNIQUE KEY `HISTORIAL_SUELDO_UNIQUE` (`ID_EMPLEADO`,`PERIODO`),
  CONSTRAINT `historial_sueldo_empleado` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_TRB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `labores` (
  `ID_LAB` int NOT NULL AUTO_INCREMENT,
  `COD_LAB` varchar(3) NOT NULL,
  `NOM_LAB` varchar(30) NOT NULL,
  `ID_TIPO_JORNADA` int NOT NULL COMMENT 'TIPO DE JORNADA: DIURNA, NOCTURNA',
  `VAL_LAB` decimal(17,2) DEFAULT '0.00' COMMENT 'VALOR DE LA LABOR, MONTO DE LA LABOR',
  `FAC_LAB` decimal(17,7) DEFAULT '0.0000000' COMMENT 'FACTOR DE LA LABOR DEPENDE DEL TIPO DE LABOR SI ES FACTOR EN TIPO DE LABOR SE ACTIVA ESTE CAMPO',
  `ID_TIPO_PAGO` int NOT NULL COMMENT 'TIPO DE LABOR:\nD : DEFINIDO POR EL USUARIO\nF: FACTOR\nH: HORA\nv: VALOR',
  `ID_CUENTA` int NOT NULL,
  PRIMARY KEY (`ID_LAB`),
  UNIQUE KEY `codigo_labor_unique` (`COD_LAB`),
  UNIQUE KEY `nombre_labor_unique` (`NOM_LAB`),
  KEY `fk_tipo_jornada_idx` (`ID_TIPO_JORNADA`),
  KEY `fk_labores_tipo_labor` (`ID_TIPO_PAGO`),
  CONSTRAINT `fk_labores_tipo_labor` FOREIGN KEY (`ID_TIPO_PAGO`) REFERENCES `tipo_pago` (`ID_TIPO_PAGO`),
  CONSTRAINT `fk_tipo_jornada` FOREIGN KEY (`ID_TIPO_JORNADA`) REFERENCES `tipo_jornada` (`id_tipo_jornada`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `mdescuentos` (
  `ID_MDESCUENTOS` int NOT NULL AUTO_INCREMENT,
  `ID_EMPLEADO` int NOT NULL,
  `ID_DESCUENTO` int NOT NULL,
  `DESCRIPCION_DESCUENTO` varchar(30) NOT NULL,
  `CANT_DESCUENTO` decimal(8,2) NOT NULL,
  `FECHA_DESCUENTO` date NOT NULL,
  `MON_DESCUENTO` decimal(17,2) NOT NULL,
  `ID_CUENTA` int NOT NULL,
  `ID_NOMINA` int DEFAULT NULL,
  `ID_TIPO_PAGO` int NOT NULL,
  PRIMARY KEY (`ID_MDESCUENTOS`),
  UNIQUE KEY `mdescuentos_unique` (`ID_EMPLEADO`,`ID_DESCUENTO`,`FECHA_DESCUENTO`),
  KEY `fk_mdescuentos_empleado_idx` (`ID_EMPLEADO`),
  KEY `fk_mdescuentos_descuentos_idx` (`ID_DESCUENTO`),
  KEY `fk_mdescuentos_tipopago_idx` (`ID_TIPO_PAGO`),
  CONSTRAINT `fk_mdescuentos_descuentos` FOREIGN KEY (`ID_DESCUENTO`) REFERENCES `descuento` (`ID_DESCUENTO`),
  CONSTRAINT `fk_mdescuentos_empleado` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_TRB`),
  CONSTRAINT `fk_mdescuentos_tipopago` FOREIGN KEY (`ID_TIPO_PAGO`) REFERENCES `tipo_pago` (`ID_TIPO_PAGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `mlabores` (
  `ID_MLABORES` int NOT NULL AUTO_INCREMENT,
  `ID_EMPLEADO` int NOT NULL,
  `ID_LABOR` int NOT NULL,
  `DESCRIPCION_LAB` varchar(30) NOT NULL,
  `CANTIDAD_LAB` decimal(7,2) NOT NULL,
  `FECHA_LABOR` date NOT NULL,
  `MONTO_LABOR` decimal(17,2) NOT NULL,
  `ID_CUENTA` int DEFAULT NULL,
  `ID_NOMINA` int DEFAULT NULL,
  `ISR` varchar(1) NOT NULL,
  `ID_TIPO_PAGO` int NOT NULL,
  PRIMARY KEY (`ID_MLABORES`,`CANTIDAD_LAB`),
  UNIQUE KEY `mlabores` (`ID_EMPLEADO`,`ID_LABOR`,`FECHA_LABOR`),
  KEY `FK_MLABORES_TIPO_PAGO_idx` (`ID_TIPO_PAGO`),
  KEY `FK_MLABORES_LABORES` (`ID_LABOR`),
  CONSTRAINT `FK_MLABORES_EMPLEADO` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_TRB`),
  CONSTRAINT `FK_MLABORES_LABORES` FOREIGN KEY (`ID_LABOR`) REFERENCES `labores` (`ID_LAB`),
  CONSTRAINT `FK_MLABORES_TIPO_PAGO` FOREIGN KEY (`ID_TIPO_PAGO`) REFERENCES `tipo_pago` (`ID_TIPO_PAGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `parametro` (
  `PARAMETRO_ID` int NOT NULL AUTO_INCREMENT,
  `PERIODO` int NOT NULL,
  `EXCENTO` decimal(50,2) NOT NULL,
  `RANGO_INICIAL15` decimal(50,2) NOT NULL,
  `RANGO_FINAL15` decimal(50,2) NOT NULL,
  `RANGO_INICIAL20` decimal(50,2) NOT NULL,
  `RANGO_FINAL20` decimal(50,2) NOT NULL,
  `RANGO_INICIAL25` decimal(50,2) NOT NULL,
  `RANGO_FINAL25` decimal(50,2) NOT NULL,
  `SUELDO_PROMEDIO` decimal(20,2) NOT NULL,
  PRIMARY KEY (`PARAMETRO_ID`),
  UNIQUE KEY `PERIODO_UNIQUE` (`PERIODO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `planilla` (
  `ID_PLANILLA` int NOT NULL AUTO_INCREMENT,
  `COD_PLANILLA` varchar(10) NOT NULL,
  `FECHA` date NOT NULL,
  `ID_EMPLEADO` int NOT NULL,
  `SUELDO` decimal(17,2) DEFAULT NULL,
  `DIARIO` decimal(17,2) DEFAULT NULL,
  `LABORES` decimal(17,2) DEFAULT NULL,
  `AUMENTO` decimal(17,2) DEFAULT NULL,
  `SALARIO` decimal(17,2) DEFAULT NULL,
  `IHSS` decimal(17,2) DEFAULT NULL,
  `RAP` decimal(17,2) DEFAULT NULL,
  `ISR` decimal(17,2) DEFAULT NULL,
  `AUSENCIAS` decimal(17,2) DEFAULT NULL,
  `SEPTIMO` decimal(17,2) DEFAULT NULL,
  `DEDUCCIONES` decimal(17,2) DEFAULT NULL,
  `PRESTAMO` decimal(17,2) DEFAULT NULL,
  `DESCUENTOS` decimal(17,2) DEFAULT NULL,
  `SALARIO_NETO` decimal(17,2) DEFAULT NULL,
  PRIMARY KEY (`ID_PLANILLA`),
  UNIQUE KEY `PRESTAMOS_UNIQUE` (`COD_PLANILLA`,`FECHA`,`ID_EMPLEADO`),
  KEY `FK_PLANILLA_EMPLEADO` (`ID_EMPLEADO`),
  CONSTRAINT `FK_PLANILLA_EMPLEADO` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `empleado` (`ID_TRB`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `prestamo` (
  `ID_PRESTAMO` int NOT NULL AUTO_INCREMENT,
  `CODIGO` varchar(5) NOT NULL,
  `ID_EMPLEADO` int NOT NULL,
  `FECHA` date NOT NULL,
  `DESCRIPCION` varchar(40) DEFAULT NULL,
  `MONTO` decimal(17,2) NOT NULL,
  `ESTADO` varchar(1) NOT NULL,
  `CUOTA` decimal(17,2) DEFAULT NULL,
  `CUOTA_MES` decimal(17,2) DEFAULT NULL,
  `ID_TIPO_PAGO` int NOT NULL,
  `TIEMPO` int NOT NULL,
  `P_ANT` decimal(17,2) DEFAULT NULL,
  `P_DEB` decimal(17,2) DEFAULT NULL,
  `P_CRED` decimal(17,2) DEFAULT NULL,
  `P_ACT` decimal(17,2) DEFAULT NULL,
  `COD_CPRES` varchar(8) DEFAULT NULL,
  `ACCESO` varchar(24) DEFAULT NULL,
  PRIMARY KEY (`ID_PRESTAMO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

-- Volvemos a encender las llaves foráneas para mantener la integridad
SET FOREIGN_KEY_CHECKS = 1;