//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nomina.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nomina.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buscar_empleado {
            get {
                object obj = ResourceManager.GetObject("buscar empleado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buscar_empleado1 {
            get {
                object obj = ResourceManager.GetObject("buscar empleado1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE DATABASE IF NOT EXISTS sistema_nomina
        ///CHARACTER SET utf8mb4
        ///COLLATE utf8mb4_unicode_ci;
        ///
        ///USE sistema_nomina;
        ///
        ///
        ///SET FOREIGN_KEY_CHECKS = 0;
        ///
        ///CREATE TABLE `tipo_aumento` (
        ///  `TIPO_AUMENTO_ID` int NOT NULL AUTO_INCREMENT,
        ///  `DESCRIPCION` varchar(45) DEFAULT NULL,
        ///  PRIMARY KEY (`TIPO_AUMENTO_ID`)
        ///) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
        ///
        ///CREATE TABLE `tipo_empleado` (
        ///  `ID_TIPO_EMPLEADO` int NOT NULL AUTO_INCREMENT,
        ///  `DESCRIPCION` varchar(1000) NOT NULL,
        ///  PRIMARY KE [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string estructura_empresas {
            get {
                return ResourceManager.GetString("estructura_empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lupa {
            get {
                object obj = ResourceManager.GetObject("lupa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a use sistema_nomina;
        ///
        ///CREATE  FUNCTION `existe_aumento`(
        ///  P_AUMENTOS_ID INT,
        ///   P_ID_EMPLEADO INT,
        ///   P_FEC_AUM DATE,
        ///   P_ID_CAT INT
        ///) RETURNS int
        ///    DETERMINISTIC
        ///BEGIN
        ///  declare v_salida int;
        ///  SET P_AUMENTOS_ID = COALESCE(P_AUMENTOS_ID, -1);
        ///    SELECT COUNT(ID_EMPLEADO) INTO v_salida FROM aumentos 
        ///    WHERE 
        ///    AUMENTOS_ID &lt;&gt; P_AUMENTOS_ID 
        ///    AND ID_EMPLEADO =P_ID_EMPLEADO
        ///    AND FECHA= P_FEC_AUM
        ///        AND ID_CATEGORIA = P_ID_CAT;
        ///RETURN v_salida;
        ///END ;
        ///
        ///
        ///
        ///
        ///CREATE  FUNCT [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string procedimientos__almacenados_empresas {
            get {
                return ResourceManager.GetString("procedimientos__almacenados_empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_find_client_user_16693 {
            get {
                object obj = ResourceManager.GetObject("search_find_client_user_16693", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_find_client_user_166931 {
            get {
                object obj = ResourceManager.GetObject("search_find_client_user_166931", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_find_lupa_21889 {
            get {
                object obj = ResourceManager.GetObject("search_find_lupa_21889", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_find_lupa_218891 {
            get {
                object obj = ResourceManager.GetObject("search_find_lupa_218891", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
